# Default values for workbench.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workbench:
  dev:
    enabled: false
    uisrc: ""
  name: "Labs Workbench"
  domain: "local.ndslabs.org"
  subdomain_prefix: "www"
  volume_name: "global"
  support_email: "ndslabs-support@nationaldataservice.org"
  require_account_approval: true
  specs:
    repo: "https://github.com/nds-org/ndslabs-specs.git"
    branch: "master"
  images:
    webui: "ndslabs/angular-ui:1.1.0"
    apiserver: "ndslabs/apiserver:1.1.0"
    etcd: "ndslabs/etcd:2.2.5"
    smtp: "namshi/smtp:latest"
  persistence:
    accessMode: "ReadWriteMany"
    size: "1Gi"
  
# FIXME: This has not been tested
oauth:
  enabled: false
  signin_url: ""
  auth_url: ""

rbac:
  enabled: true

smtp:
  # Specify host/port to use standalone SMTP
  host: 
  port: 
  # Specify user/pass to use Gmail SMTP
  user: 
  pass: 

# Insert your tls certificate and private key here
# NOTE: To generate a new certificate, you can run the helper script included with this chart:
#    ./generate-self-signed-cert.sh [DOMAIN]
#
# If you do not specify a domain, you will be prompted for one
tls:
  secretName: "ndslabs-tls-secret"
  cert: |
    -----BEGIN CERTIFICATE-----
    PASTE CERTIFICATE CONTENTS HERE
    -----END CERTIFICATE-----

  key: |
    -----BEGIN RSA PRIVATE KEY-----
    PASTE PRIVATE KEY CONTENTS HERE
    -----END RSA PRIVATE KEY-----
    
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
