---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  storageClassName: ""
  capacity:
    # Update storage with the size of the GCE Disk
    storage: <GCE Disk Size>
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    # Update pdName with the GCE Disk name
    pdName: <GCE Disk Name>
    fsType: ext4
  # Replace the namespace with the namespace the nfs-server-provisioner Helm Chart will be deployed in and replace the
  # name with the name of the nfs-server-provisioner PersistentVolumeClaim, if you named the Helm Chart nfs-server-provisioner
  # then the PVC will be named data-nfs-server-provisioner-0
  claimRef:
    namespace: default
    name: data-nfs-server-provisioner-0
