{{ if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
rules:
- apiGroups: ["", "extensions", "apps", "batch", "policy", "rbac.authorization.k8s.io"]
  resources: ["componentstatuses", "persistentvolumeclaims", "replicasets", "deployments", "events", "endpoints", "pods", "pods/log", "namespaces", "services", "replicationcontrollers", "secrets", "resourcequotas", "limitranges"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["ndslabs-config"]
  verbs: ["get", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io
---
{{ end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    component: {{ .Release.Name }}
spec:
  selector:
    component: {{ .Release.Name }}
  ports:
    - port: 80
      name: webui
      protocol: TCP
      targetPort: 3000
    - port: 30001
      name: api
      protocol: TCP
    - name: smtp
      port: 25
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-auth
  namespace: {{ .Release.Namespace }}
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/auth-url": "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/cauth/auth"
    "nginx.ingress.kubernetes.io/auth-signin": "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/login/"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
spec:
  tls:
  - hosts:
    - {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    http:
      paths:
      - path: /logs
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /dashboard
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-open
  namespace: {{ .Release.Namespace }}
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/ssl-redirect": "true"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "true"
spec:
  tls:
  - hosts:
    - {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    secretName: {{ .Values.tls.secretName }}
  rules:
  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 30001
      - path: /login
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /landing
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /dashboard
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /cauth
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /shared
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /bower_components
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /node_modules
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /asset
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
      - path: /ConfigModule.js
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://{{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}/landing/"
  name: {{ .Release.Name }}-root
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.workbench.subdomain_prefix }}.{{ .Values.workbench.domain }}
    secretName: {{ .Values.tls.secretName }}
{{- if .Values.workbench.etcd_storage.presistant | default false }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-etcd
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.workbench.etcd_storage.size | quote }}
  accessModes:
    - {{ .Values.workbench.etcd_storage.accessMode | quote }}
  {{- if .Values.workbench.etcd_storage.ebs_volume_id | default nil }}
  awsElasticBlockStore:
    volumeID: {{ .Values.workbench.etcd_storage.ebs_volume_id | quote }}
  {{- end }}
  {{- if .Values.workbench.etcd_storage.gce_persistent_disk_name | default nil }}
  gcePersistentDisk:
    pdName: {{ .Values.workbench.etcd_storage.gce_persistent_disk_name | quote }}
  {{- end }}
    fsType: ext4
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ .Release.Name }}-etcd
{{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etcd
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.workbench.etcd_storage.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.workbench.etcd_storage.storageClass | quote }}
  {{- end }}
spec:
  {{- if .Values.workbench.etcd_storage.presistant | default false }}
  storageClassName: ""
  volumeName: {{ .Release.Name }}-etcd
  {{- end }}
  accessModes:
    - {{ .Values.workbench.etcd_storage.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.workbench.etcd_storage.size | quote }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Release.Name }}
  template:
    metadata:
      labels:
        component: {{ .Release.Name }}
    spec:
{{ if .Values.rbac.enabled }}
      serviceAccountName: {{ .Release.Name }}
{{ end }}
      volumes:
       - persistentVolumeClaim:
            claimName: {{ .Release.Name }}-etcd
         name: varetcd
{{ if .Values.workbench.dev.enabled | default false }}
       - hostPath:
            path: "{{ .Values.workbench.dev.uisrc }}"
         name: uisrc
{{ end }}
      containers:
      - name: webui
        image: {{ required "Must specify an image for ndslabs-webui" .Values.workbench.images.webui }}
        imagePullPolicy: Always
{{ if .Values.workbench.dev.enabled | default false }}
        volumeMounts: 
        - name: uisrc
          mountPath: "/home"
{{ end }}
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
          - name: DOMAIN
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.domain
          - name: APISERVER_SECURE
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: tls.enable
          - name: SIGNIN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.signin_url
          - name: ANALYTICS_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.analytics_tracking_id
          - name: SUPPORT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.support_email
          - name: APISERVER_HOST
            value: "{{ .Values.workbench.subdomain_prefix }}.$(DOMAIN)"
          - name: NDSLABS_APISERVER_SERVICE_PORT
            value: "30001"
          - name: APISERVER_PATH
            value: "/api"
        readinessProbe:
          httpGet:
            path: /asset/png/favicon-2-32x32.png
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 120

      - name: apiserver
        image: {{ required "Must specify an image for ndslabs-apiserver" .Values.workbench.images.apiserver }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 30001
          protocol: TCP
        - containerPort: 30002
          protocol: TCP
        env:
          - name: SHARED_VOLUME_PATH
            value: "/tmp/shared"
          - name: SUPPORT_EMAIL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.support_email
          - name: REQUIRE_APPROVAL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.require_account_approval
          - name: DOMAIN
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.domain
          - name: SPEC_GIT_REPO
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: git.spec_repo
          - name: SPEC_GIT_BRANCH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: git.spec_branch
          - name: SIGNIN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.signin_url
          - name: AUTH_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.auth_url
          - name: CORS_ORIGIN_ADDR
            value: "https://{{ .Values.workbench.subdomain_prefix }}.$(DOMAIN)"
          - name: ETCD_ADDR
            value: "localhost:4001"
          - name: KUBERNETES_ADDR
            value: "https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT_HTTPS)"
          - name: INGRESS
            value: "LoadBalancer"
          - name: SERVICE_TIMEOUT
            value: "10"
          - name: TOKEN_PATH
            value: "/var/run/secrets/kubernetes.io/serviceaccount/token"
          - name: SMTP_HOST
            value: "localhost"
          - name: SMTP_TLS
            value: "false"
          - name: HOME_PVC_SUFFIX
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.home_storage.home_pvc_suffix
          - name: PVC_STORAGE_CLASS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: workbench.home_storage.pvc_storage_class
      - name: etcd
        image: {{ required "Must specify an image for ndslabs-etcd" .Values.workbench.images.etcd }}
        command:
        - /usr/local/bin/etcd
        - --bind-addr=0.0.0.0:4001
        - --advertise-client-urls=http://127.0.0.1:4001
        - --data-dir=/var/etcd/data
        ports:
        - containerPort: 4001
          name: server
          protocol: TCP
        volumeMounts: 
        - name: varetcd
          mountPath: /var/etcd
      - name: smtp
        image: {{ required "Must specify an image for ndslabs-smtp" .Values.workbench.images.smtp }}
        ports:
        - containerPort: 25
          name: server
          protocol: TCP
        env:
          - name: MAILNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.host
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.port
          - name: GMAIL_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.gmail_user
          - name: GMAIL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.gmail_pass
          - name: SES_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.aws_ses_user
          - name: SES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.aws_ses_password
          - name: SMARTHOST_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.smarthost_address
          - name: SMARTHOST_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.smarthost_port
          - name: SMARTHOST_USER
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.smarthost_user
          - name: SMARTHOST_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}
                key: smtp.smarthost_password
